
pipeline {
  agent any

  stages {
 
    stage('docker image') {
       
      steps {
       dir('bulletin-board-app'){
       withDockerRegistry([ credentialsId: "Docker_creds", url: "https://index.docker.io/v1/" ]) {
       sh 'docker build -t stephanieawono86/java-nodejs-jenkins . -f Dockerfile'
       sh 'docker push stephanieawono86/java-nodejs-jenkins'
        
        }
       
        
        }
         
      }
     }
      }
      }
